### ISSUE TITLE
[Feature] 교과 추천 도메인 서비스 개발

### ISSUE THREAD

**Issue by jinhyeok15** [bitstep-Be-A/hais-react#13]
- [x] test(#13): 교과추천 도메인 인터페이스 업데이트 및 firebase storage connection test 진행
- [x] feat(#13): schema type 정의
- [x] feat(#13): 교과 탐색 페이지 연결 및 SubjectSearch ui/ux 추가

- hotfix!: routes.ts 모듈 위치 변경 policy/routes.ts -> routes.ts
- hotfix!: rename context to service
- hotfix!: rename schema/atom -> schema/atoms && schema/type -> schema/types
- hotfix!: rename domain/subject-recommend -> domain/subject

- [x] feat(#13): 교과 탐색 필터 부분 서비스 개발 및 ux 구현
