### ISSUE TITLE
[Feature] 과목 입력 Admin 페이지 개발

### ISSUE THREAD

**Issue by jinhyeok15** [bitstep-Be-A/hais-react#42]
- [x] feat(#42): BaseContainer Sidebar, Appbar 완성
- [x] feat(#42): admin 계정 여부 확인 (접근 차단)
- [x] feat(#42): 교과 조회 테이블 component 설계 완료
- [x] feat(#42): 과목 상세 조회 / 수정 Dialog component 설계 완료
- [x] feat(#42): 공통 과목 수정 / 추가 기능 설계 완료
- [x] feat(#42): 과목 조회 쪽 firestorage -> firestore로 migration된 사항 반영 및 테이블 UI 조정 및 정렬 추가
- [x] feat(#42): 공통 과목 삭제 기능 설계 완료
- [x] feat(#42): 선택 과목 수정 / 추가 / 삭제 기능 설계 완료
